<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.103" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CountersApi.Common\CountersApi.Common.csproj" />
    </ItemGroup>

</Project>